### ISSUE TITLE
Example of todo file

### ISSUE THREAD

**Issue by anmolnagpal** [senorprogrammer/wtf#132]
|    Q        |   A
|------------ | -----
| Version     | 4.10.x
#### Support Question
Hello, I'm trying to create a todo file. But I'm not sure how exactly I have to write into it. 

I tried to use this but it's not working 

```
---
# A list of tasty fruits
fruits:
    - Apple
    - Orange
    - Strawberry
    - Mango

```

**Comment by jeangovil** [comment]
You can use to keyboard commands to create a todo list and it automatically creates the file for you.
Here is the documentation of Todo Widget:
[Todo](https://wtfutil.com/posts/modules/todo/)
By the way here is a example of todo list file: 
```
items:
- checked: true
  text: Todo 1
- checked: false
  text: Todo 2
- checked: false
  text: Todo 3
- checked: true
  text: Todo 4
```
