### ISSUE TITLE
CryptoLive widget values flash between default and fetched value

### ISSUE THREAD

**Issue by senorprogrammer** [senorprogrammer/wtf#162]
#### Summary
CryptoLive values flap between fetched number and `0.00000` every few seconds.

##### What is the current behaviour?
CryptoLive values flap between fetched number and `0.00000` every few seconds.

### How to reproduce
Use this config:

```yaml
    cryptolive:
      colors:
        from:
          name: red
          displayName: grey
        to:
          name: white
          price: green
      currencies:
        BTC:
          displayName: Bitcoin
          to:
            - CAD
            - LTC
        LTC:
          displayName: Litecoin
          to:
            - CAD
            - BTC
      enabled: true
      position:
        top: 4
        left: 5
        height: 1
        width: 1
      refreshInterval: 600
      title: " CryptoLive "
      updateInterval: 600
```
##### If the current behaviour is a bug, please provide the steps to reproduce it.
1. Add that YAML to your config file
2. Position CryptoLive somewhere you can see it

##### What do you think the expected behaviour should be?
1. Initially display `0.00000`
2. After first fetch of numeric data, display only the fetched value (i.e.: `9719.50000`)
3. No flapping between zeros and fetched values.
