### ISSUE TITLE
Not retrieving GitHub data

### ISSUE THREAD

**Issue by juliquiron** [senorprogrammer/wtf#177]
#### Summary
Data from all repositories looks empty

##### What is the current behaviour?
with the setup of the example in the web site the repository information appears in the top but all the information (issues, pr...) are empty.

### How to reproduce
```
go get -u github.com/senorprogrammer/wtf
cd $GOPATH/src/github.com/senorprogrammer/wtf
make install
make run
```
add this to the configuration:
```
github:
  enabled: true
  position:
    top: 2
    left: 3
    height: 2
    width: 2
  refreshInterval: 300
  repositories:
    wesker-api: "UmbrellaCorp"
    wtf: "senorprogrammer"
  username: "senorprogrammer"
```
run `wtf`

I guess is the default 'thing' so how can I get debug data to provide it here?

thanks so much.

**Comment by senorprogrammer** [comment]
This is an obvious question, but did you change the values in `repositories` and `username` to your own values?

**Comment by juliquiron** [comment]
this is my testing setting:
```
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    github:
      enabled: true
      position:
        top: 2
        left: 3
        height: 2
        width: 2
      refreshInterval: 300
      repositories:
        wesker-api: "UmbrellaCorp"
        wtf: "senorprogrammer"
      username: "juliquiron"
    security:
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 3600
```
I set up my github user, but not the repositories as long as I want to get informed of some public repoistories as well. Is what is designed for, right?

thanks so much.
