### ISSUE TITLE
Script don't run config

### ISSUE THREAD

**Issue by luan0ap** [senorprogrammer/wtf#190]
|    Q        |   A
|------------ | -----
| Version     | 0.0.6
#### Support Question
I tried run the API of the github in the script, but they not recognizes the`.yml` file. Then I tried run other config just with `ipinfo` no results, he don't show :/. I think that not is a problem in the app, but in my configs.

**Comment by senorprogrammer** [comment]
Paste your config here, let's take a look.

**Comment by luan0ap** [comment]
Here
```
wtf:
  ipinfo:
    colors:
      name: red
      value: white
    enabled: true
    position:
      top: 1
      left: 3
      height: 1
      width: 1
    refreshInterval: 150
  github:
    enabled: true
    position:
      top: 2
      left: 3
      height: 2
      width: 2
    refreshInterval: 300	
    username: "luan0ap"
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        "São Paulo": "America/Sao_Paulo"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    security:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    status:
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      refreshInterval: 1
    system:
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
    textfile:
      enabled: true
      filePath: "~/.wtf/config.yml"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 30
```

**Comment by senorprogrammer** [comment]
You have `ipinfo` and `github` outside the `mods` section. Module definitions need to be inside there.

Move all of this into `mods` and it should work:
```
  ipinfo:
    colors:
      name: red
      value: white
    enabled: true
    position:
      top: 1
      left: 3
      height: 1
      width: 1
    refreshInterval: 150
  github:
    enabled: true
    position:
      top: 2
      left: 3
      height: 2
      width: 2
    refreshInterval: 300	
    username: "luan0ap"
```
