### ISSUE TITLE
cmdrunner doesn't diplay colors of terminal output

### ISSUE THREAD

**Issue by varac** [senorprogrammer/wtf#201]
#### What's the problem?

I'm using cmdrunner to display a colored [khal](http://khal.readthedocs.io/en/latest/) output, but the colors are stripped by cmdrunner unfortunatly.

#### How did you expect it to behave?

cmdrunner should display the colors exactly like the terminal output of a command looks like.

**Comment by varac** [comment]
## Steps to reproduce

Use this cmdrunner example:

```
    cmdrunner:                                                                                                                                                                           
      # cmd: "khal"                                                                                                                                                                      
      cmd: '/bin/echo'                                                                                                                                                                   
      args: ["\x1b[31;4mHello\x1b[0m"]                                                                                                                                                   
      # args: ["-g", "batt"]                                                                                                                                                             
      enabled: true                                                                                                                                                                      
      position:                                                                                                                                                                          
        top: 2                                                                                                                                                                           
        left: 1                                                                                                                                                                          
        height: 1                                                                                                                                                                        
        width: 2                                                                                                                                                                         
      refreshInterval: 30    
```

This will produce this output:

![screenshot from 2018-06-10 19-40-37](https://user-images.githubusercontent.com/488213/41204544-2f435d20-6ce6-11e8-81e0-26ee61e6e8a8.png)
