### ISSUE TITLE
Trello Integration

### ISSUE THREAD

**Issue by PidgeyL** [senorprogrammer/wtf#204]
#### What problem does this solve?
This could add the possibility to add Trello boards to the dashboard in the same way the Jira widget does, mostly for hobbyists (like myself)

#### How do envision it working?
This could work the same way as the Jira widget

**Comment by retgits** [comment]
I'd love to help build this because I'm using Trello for the exact same reason! I have a prototype on my own machine which would let you get the cards of one or multiple lists on a board.

Required ENV Variables
```bash
Key: WTF_TRELLO_APP_KEY
Value: Your Trello App Key
Key: WTF_TRELLO_ACCESS_TOKEN
Value: Your Trello Access Token
```

_You can get your API key at: https://trello.com/app-key._

Configuration for one list
```yaml
trello: 
  board: Main
  enabled: true
  list: "Todo"
  position: 
    height: 1
    left: 2
    top: 0
    width: 1
  refreshInterval: 3600
  username: myname
```

Configuration for multiple lists
```yaml
trello: 
  board: Main
  enabled: true
  list: ["Todo", "Done"]
  position: 
    height: 1
    left: 2
    top: 0
    width: 1
  refreshInterval: 3600
  username: myname
```

Attributes:
* board: The name of the Trello board.
* enabled: Determines whether or not this module is executed and if its data displayed onscreen. Values: true, false.
* list: The Trello lists to get the cards from.
* position: Defines where in the grid this module’s widget will be displayed. 
* refreshInterval: How often, in seconds, this module will update its data. Values: A positive integer, 0..n.
* username: Your Trello username

I've built it this way mostly because it solves my immediate needs. Thoughts / comment are welcome 😄
