### ISSUE TITLE
"todo" modle does not work on Ubuntu18.04 LTS with Zsh or Bash shell 

### ISSUE THREAD

**Issue by thesunnysky** [senorprogrammer/wtf#255]
#### What's the problem?
I have installed wtf on my pc with OS Ubuntu 18.04 LTS，the default module such as Clocks，System，Secutiry and TextFile works good，but the todo module doesn't  work， my  ~/.config/wtf :
```
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Avignon: "Europe/Paris"
        Barcelona: "Europe/Madrid"
        Dubai: "Asia/Dubai"
        Vancouver: "America/Vancouver"
        Toronto: "America/Toronto"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    security:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      refreshInterval: 3600
    system:
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 3600
    textfile:
      enabled: true
      filePath: "~/.config/wtf/config.yml"
      position:
        top: 1
        left: 1
        height: 1
        width: 1
      refreshInterval: 30
```
and the todo.yaml is generated automatically( todo.yaml is empty)
the question is :
when I run wtf, the todo block is shown in my terminal(gnome-terminal) , but neither the keyboard commands works, nothing happened when I press key "n" or any other command key. 
my go version:go version go1.10.3 linux/amd64
