### ISSUE TITLE
TODOIST

### ISSUE THREAD

**Issue by linux923344** [senorprogrammer/wtf#303]
#### What's the problem?
I configured it. It shows INBOX but it is blank :(

#### How did you expect it to behave?
Help :3

#### Operating system 
OS: Arch

#### Terminal program & version
Konsole

#### WTF version
Dev
![screenshot_20180822_121247](https://user-images.githubusercontent.com/10187235/44457867-b87bc800-a604-11e8-89a0-72daaaa088d2.png)

**Comment by anandsudhir** [comment]
Are you sure you have the correct project id/number and the apiKey in the config? 

I have something like this below and my widget loads up just fine.

```yaml
    todoist:
      apiKey: "my api key"
      enabled: true
      position:
        top: 0
        left: 3
        height: 1
        width: 2
      projects:
      - 123456789
      - 987654321
      refreshInterval: 300
```

**Comment by linux923344** [comment]
Yeah i'm sure ^-^
 ```
    todoist:
      apiKey: "MyAPI"
      enabled: true
      position:
        top: 0
        left: 2
        height: 5
        width: 1
      projects:
        - 2179824787
      refreshInterval: 10
```

**Comment by linux923344** [comment]
Also I have problem with Google Calendar. I didnt get error auth. It is going well but when i run it it shows like in the Screenshot :/

**Comment by linux923344** [comment]
```
    gcal: 
      colors:
        title: "red"
        description: "lightblue"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "kaczor982@gmail.com"
      enabled: true
      eventCount: 12
      multiCalendar: true
      position:
        top: 0
        left: 1
        height: 5
        width: 1
      refreshInterval: 300
      secretFile: "$PATH/token.json"                                                                      
      showDeclined: true
      withLocation: true
```

**Comment by anandsudhir** [comment]
How about we take the discussion over to https://gitter.im/wtfutil/Lobby?

**Comment by senorprogrammer** [comment]
Is this issue still relevant?

**Comment by linux923344** [comment]
Yep :/

**Comment by senorprogrammer** [comment]
Here's an example of my Todoist config:
```
    todoist:
      apiKey: "22f089e35fb39aaxxxx45c2ee53d37e800b37cf8"
      projects:
        - 2176374229
        - 2170373228
      enabled: true
      position:
        top: 4
        left: 3
        height: 3
        width: 1
      refreshInterval: 300
```
Does the Todoist module show you any error in it? What do you see?
