### ISSUE TITLE
Need help setting up Google Calendar

### ISSUE THREAD

**Issue by ngocphamm** [senorprogrammer/wtf#83]
I think I've tried what I could... Please help

My `config.yml`. Yes, only with gcal module. That's all I need for now.
```
wtf:
  colors:
    border:
      Focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
  mods:
    gcal:
      colors:
          title: "red"
          description: "lightblue"
          past: "gray"
      conflictIcon: "🚨"
      currentIcon: "💥"
      withLocation: false
      displayResponseStatus: true
      email: "<myemail>"
      enabled: true
      eventCount: 5
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 300
      secretFile: "~/.wtf/gcal/client_secret.json"
```

I have that `client_secret.json` by following [this](https://developers.google.com/calendar/quickstart/go), and I confirm the credentials work fine with a REST Client (Paw).

However when I run `wtf` in my command line, I see a blank screen. `Ctrl + C` twice to get out of the program and I see something like this on the screen.

```
Go to the following link in your browser then type the authorization code:

https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=<my-client-id>&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&state=state-token
```

I could follow the link and generate the authentication token, but I have no way to "paste" it back to `wtf`.

Also, aren't the ENV variables NOT required anymore if there's the `client_secret.json`? They are basically the same stuff. https://wtfutil.com/posts/modules/gcal/

Thank you!
